/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ApiResponseUserVO,
  ApiResponseVerificationCodeVO,
  ApiResponseVoid,
  GetVerificationCodeParams,
  UserLoginRequest,
  UserRegisterRequest,
} from '.././models'

import { axiosInstance } from '../../../../axios-instance'

export const getUserController = () => {
  /**
   * 用户注册接口
   */
  const userRegister = (userRegisterRequest: UserRegisterRequest) => {
    return axiosInstance<ApiResponseUserVO>({
      url: `/sys_user/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userRegisterRequest,
    })
  }
  /**
   * 用户登录接口
   */
  const userLogin = (userLoginRequest: UserLoginRequest) => {
    return axiosInstance<ApiResponseUserVO>({
      url: `/sys_user/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userLoginRequest,
    })
  }
  /**
   * 用户登出接口
   */
  const logout = () => {
    return axiosInstance<ApiResponseVoid>({ url: `/sys_user/logout`, method: 'GET' })
  }
  /**
   * 用于获取验证码，返回一个验证码id。首次访问可以不传，二次访问必须传！
   */
  const getVerificationCode = (params?: GetVerificationCodeParams) => {
    return axiosInstance<ApiResponseVerificationCodeVO>({
      url: `/sys_user/getVerificationCode`,
      method: 'GET',
      params,
    })
  }
  return { userRegister, userLogin, logout, getVerificationCode }
}
export type UserRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserController>['userRegister']>>
>
export type UserLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserController>['userLogin']>>
>
export type LogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserController>['logout']>>
>
export type GetVerificationCodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserController>['getVerificationCode']>>
>
