/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultSysRolePermissionVO } from './pageResultSysRolePermissionVO'

export interface ApiResponsePageResultSysRolePermissionVO {
  code?: number
  message?: string
  data?: PageResultSysRolePermissionVO
}
