/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SysRoleVO } from './sysRoleVO'

export interface ApiResponseSysRoleVO {
  code?: number
  message?: string
  data?: SysRoleVO
}
