/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VerificationCodeVO } from './verificationCodeVO'

export interface ApiResponseVerificationCodeVO {
  code?: number
  message?: string
  data?: VerificationCodeVO
}
