/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultCarTypeVO } from './pageResultCarTypeVO'

export interface ApiResponsePageResultCarTypeVO {
  code?: number
  message?: string
  data?: PageResultCarTypeVO
}
