/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SysMenuTreeVO } from './sysMenuTreeVO'

export interface ApiResponseListSysMenuTreeVO {
  code?: number
  message?: string
  data?: SysMenuTreeVO[]
}
