/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ApiResponseObject {
  code?: number
  message?: string
  data?: unknown
}
