/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ForumReplyVO } from './forumReplyVO'

export interface ApiResponseForumReplyVO {
  code?: number
  message?: string
  data?: ForumReplyVO
}
