/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SysPermissionVO } from './sysPermissionVO'

export interface ApiResponseSysPermissionVO {
  code?: number
  message?: string
  data?: SysPermissionVO
}
