/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserVO } from './userVO'

export interface ApiResponseUserVO {
  code?: number
  message?: string
  data?: UserVO
}
