/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ForumPostDetailVO } from './forumPostDetailVO'

export interface ApiResponseForumPostDetailVO {
  code?: number
  message?: string
  data?: ForumPostDetailVO
}
