/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SysRolePermissionVO } from './sysRolePermissionVO'

export interface ApiResponseSysRolePermissionVO {
  code?: number
  message?: string
  data?: SysRolePermissionVO
}
