/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CarTypeVO } from './carTypeVO'

export interface ApiResponseCarTypeVO {
  code?: number
  message?: string
  data?: CarTypeVO
}
