/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultSysUserRoleVO } from './pageResultSysUserRoleVO'

export interface ApiResponsePageResultSysUserRoleVO {
  code?: number
  message?: string
  data?: PageResultSysUserRoleVO
}
