/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultQaQuestionVO } from './pageResultQaQuestionVO'

export interface ApiResponsePageResultQaQuestionVO {
  code?: number
  message?: string
  data?: PageResultQaQuestionVO
}
