/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SysUserVO } from './sysUserVO'

export interface ApiResponseSysUserVO {
  code?: number
  message?: string
  data?: SysUserVO
}
