/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultSysRoleVO } from './pageResultSysRoleVO'

export interface ApiResponsePageResultSysRoleVO {
  code?: number
  message?: string
  data?: PageResultSysRoleVO
}
