/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QaQuestionDetailVO } from './qaQuestionDetailVO'

export interface ApiResponseQaQuestionDetailVO {
  code?: number
  message?: string
  data?: QaQuestionDetailVO
}
