/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultForumPostVO } from './pageResultForumPostVO'

export interface ApiResponsePageResultForumPostVO {
  code?: number
  message?: string
  data?: PageResultForumPostVO
}
