/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BaseCityVO } from './baseCityVO'

export interface ApiResponseBaseCityVO {
  code?: number
  message?: string
  data?: BaseCityVO
}
