/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultCarBrandVO } from './pageResultCarBrandVO'

export interface ApiResponsePageResultCarBrandVO {
  code?: number
  message?: string
  data?: PageResultCarBrandVO
}
