/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CarBrandVO } from './carBrandVO'

export interface ApiResponseCarBrandVO {
  code?: number
  message?: string
  data?: CarBrandVO
}
