/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QaAnswerVO } from './qaAnswerVO'

export interface ApiResponseQaAnswerVO {
  code?: number
  message?: string
  data?: QaAnswerVO
}
