/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultSysPermissionVO } from './pageResultSysPermissionVO'

export interface ApiResponsePageResultSysPermissionVO {
  code?: number
  message?: string
  data?: PageResultSysPermissionVO
}
