/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageResultSysUserVO } from './pageResultSysUserVO'

export interface ApiResponsePageResultSysUserVO {
  code?: number
  message?: string
  data?: PageResultSysUserVO
}
