/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 城市返回对象
 */
export interface BaseCityVO {
  /** 主键ID */
  id?: number
  /** 城市名称 */
  cityName?: string
  /** 所属省份 */
  provinceName?: string
  /** 城市编码 */
  cityCode?: string
  /** 状态:0-停用,1-启用 */
  status?: string
  /** 排序值，越小越靠前 */
  sortOrder?: number
  /** 备注 */
  remark?: string
  /** 创建时间 */
  createdAt?: string
  /** 更新时间 */
  updatedAt?: string
}
