/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 更新城市请求体
 */
export interface BaseCityUpdateRequest {
  /**
   * 城市名称
   * @minLength 0
   * @maxLength 100
   */
  cityName?: string
  /**
   * 所属省份
   * @minLength 0
   * @maxLength 100
   */
  provinceName?: string
  /**
   * 城市编码
   * @minLength 0
   * @maxLength 20
   */
  cityCode?: string
  /**
   * 排序值，越小越靠前
   * @minimum 0
   * @maximum 9999
   */
  sortOrder?: number
  /** 状态:0-停用,1-启用 */
  status?: string
  /**
   * 备注
   * @minLength 0
   * @maxLength 255
   */
  remark?: string
}
