/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CarBrandVO {
  /** 品牌ID */
  id?: number
  /** 品牌名称 */
  brandName?: string
  /** 品牌编码 */
  brandCode?: string
  /** 品牌LOGO地址 */
  logoUrl?: string
  /** 所属国家/地区 */
  country?: string
  /** 品牌简介 */
  description?: string
  /** 状态:0-禁用,1-启用 */
  status?: string
  /** 排序值 */
  sortOrder?: number
  /** 创建时间 */
  createdAt?: string
  /** 更新时间 */
  updatedAt?: string
}
