/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 更新车辆车型请求
 */
export interface CarTypeUpdateRequest {
  /**
   * 车型名称
   * @minLength 0
   * @maxLength 100
   */
  typeName?: string
  /**
   * 车型编码
   * @minLength 0
   * @maxLength 50
   */
  typeCode?: string
  /** 车型描述 */
  description?: string
  /** 状态:0-禁用,1-启用 */
  status?: string
  /** 排序值 */
  sortOrder?: number
}
