/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 车辆车型信息
 */
export interface CarTypeVO {
  /** 车型ID */
  id?: number
  /** 车型名称 */
  typeName?: string
  /** 车型编码 */
  typeCode?: string
  /** 车型描述 */
  description?: string
  /** 状态:0-禁用,1-启用 */
  status?: string
  /** 排序值 */
  sortOrder?: number
  /** 创建时间 */
  createdAt?: string
  /** 更新时间 */
  updatedAt?: string
}
