/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DeleteUserRoleParams = {
  /**
   * 用户ID
   */
  userId: number
  /**
   * 角色ID
   */
  roleId: number
}
