/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DeleteRolePermissionParams = {
  /**
   * 角色ID
   */
  roleId: number
  /**
   * 权限ID
   */
  permissionId: number
}
