/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 帖子回复视图对象
 */
export interface ForumReplyVO {
  /** 回复ID */
  id?: number
  /** 帖子ID */
  postId?: number
  /** 回复用户ID */
  userId?: number
  /** 回复用户昵称 */
  userName?: string
  /** 回复内容 */
  content?: string
  /** 状态 */
  status?: string
  /** 创建时间 */
  createdAt?: string
}
