/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 帖子审核请求
 */
export interface ForumPostAuditRequest {
  /** 目标状态:3-通过,4-驳回,5-删除 */
  status: string
}
