/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ForumReplyVO } from './forumReplyVO'

/**
 * 帖子详情视图对象
 */
export interface ForumPostDetailVO {
  /** 帖子ID */
  id?: number
  /** 帖子标题 */
  title?: string
  /** 帖子状态 */
  status?: string
  /** 封面图 */
  coverImage?: string
  /** 浏览数 */
  viewCount?: number
  /** 点赞数 */
  likeCount?: number
  /** 评论数 */
  commentCount?: number
  /** 发帖用户ID */
  userId?: number
  /** 发帖用户昵称 */
  userName?: string
  /** 最后回复时间 */
  lastReplyTime?: string
  /** 创建时间 */
  createdAt?: string
  /** 更新时间 */
  updatedAt?: string
  /** 帖子内容 */
  content?: string
  replies?: ForumReplyVO[]
}
