/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 官方回复帖子请求体
 */
export interface ForumOfficialReplyRequest {
  /** 回复人ID，通常为管理员用户ID */
  replyUserId: number
  /**
   * 官方回复内容
   * @minLength 1
   */
  content: string
  /** 父级回复ID，可为空表示直接回复帖子 */
  parentReplyId?: number
}
