/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetVerificationCodeParams = {
  /**
   * 验证码ID，用于刷新验证码
   */
  codeId?: string
}
