/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PagePermissionsParams = {
  /**
   * 权限名称，支持模糊查询
   */
  permissionName?: string
  /**
   * 权限类型:1-目录,2-菜单,3-按钮/接口
   */
  permissionType?: number
  /**
   * 权限状态:0-禁用,1-启用
   */
  status?: number
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
