/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PageResultSysUserVO {
  /** 总记录数 */
  total?: number
  /** 当前页码 */
  current?: number
  /** 每页数量 */
  pageSize?: number
  records?: unknown[]
}
