/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PageCarTypesParams = {
  /**
   * 模糊查询关键字，支持名称、编码匹配
   */
  keyword?: string
  /**
   * 车型名称精确匹配
   */
  typeName?: string
  /**
   * 车型编码精确匹配
   */
  typeCode?: string
  /**
   * 状态:0-禁用,1-启用
   */
  status?: string
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
