/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PageUsersParams = {
  /**
   * 模糊搜索关键字，支持用户名、昵称
   */
  keyword?: string
  /**
   * 用户状态:0-禁用,1-启用
   */
  status?: string
  /**
   * 用户类型:1-管理员,2-普通用户
   */
  userType?: string
  /**
   * 按角色ID过滤用户
   */
  roleId?: number
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
