/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PageRolePermissionsParams = {
  /**
   * 角色ID
   */
  roleId?: number
  /**
   * 权限ID
   */
  permissionId?: number
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
