/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PageRolesParams = {
  /**
   * 角色编码，支持模糊查询
   */
  roleCode?: string
  /**
   * 角色名称，支持模糊查询
   */
  roleName?: string
  /**
   * 状态:0-禁用,1-启用
   */
  status?: string
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
