/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PagePostsParams = {
  /**
   * 关键字，匹配标题或内容
   */
  keyword?: string
  /**
   * 帖子状态
   */
  status?: string
  /**
   * 发帖用户ID
   */
  userId?: number
  /**
   * 开始时间
   */
  startTime?: string
  /**
   * 结束时间
   */
  endTime?: string
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
