/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PageCitiesParams = {
  /**
   * 关键字，支持按城市名称、编码模糊查询
   */
  keyword?: string
  /**
   * 城市名称，精确匹配
   */
  cityName?: string
  /**
   * 所属省份，精确匹配
   */
  provinceName?: string
  /**
   * 状态:0-停用,1-启用
   */
  status?: string
  /**
   * 当前页码
   */
  current?: number
  /**
   * 每页数量
   */
  pageSize?: number
  /**
   * 要排序的字段
   */
  sortField?: string
  /**
   * 排序顺序(默认降序)
   */
  sortOrder?: string
}
