/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 问答回答视图对象
 */
export interface QaAnswerVO {
  /** 回答ID */
  id?: number
  /** 问题ID */
  questionId?: number
  /** 回答用户ID */
  userId?: number
  /** 回答用户昵称 */
  userName?: string
  /** 回答内容 */
  content?: string
  /** 是否被采纳 */
  isAccepted?: string
  /** 回答状态 */
  status?: string
  /** 创建时间 */
  createdAt?: string
}
