/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 创建或补充问答回答的请求
 */
export interface QaAnswerCreateRequest {
  /** 关联问题ID */
  questionId: number
  /** 回答人ID，通常为管理员 */
  responderId: number
  /**
   * 回答内容
   * @minLength 1
   */
  content: string
  /** 是否将本回答标记为已解决 */
  markAsAccepted?: boolean
}
