/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QaAnswerVO } from './qaAnswerVO'

/**
 * 问答详情视图对象
 */
export interface QaQuestionDetailVO {
  /** 问题ID */
  id?: number
  /** 问题标题 */
  title?: string
  /** 问题状态 */
  status?: string
  /** 回答数量 */
  answerCount?: number
  /** 提问用户ID */
  userId?: number
  /** 提问用户昵称 */
  userName?: string
  /** 最后回答时间 */
  lastAnswerTime?: string
  /** 创建时间 */
  createdAt?: string
  /** 问题内容 */
  content?: string
  answers?: QaAnswerVO[]
}
