/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 问答状态更新请求
 */
export interface QaQuestionStatusUpdateRequest {
  /** 目标状态:1-待解答,2-解答中,3-已解决,4-已关闭 */
  status: string
}
