/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface StorageFileVO {
  /** 存储桶名称 */
  bucket?: string
  /** 对象存储路径 */
  objectKey?: string
  /** 可访问的文件URL */
  url?: string
}
