/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 前端可访问菜单树节点
 */
export interface SysMenuTreeVO {
  /** 权限ID */
  id?: string
  /** 父级ID */
  parentId?: string
  /** 显示名称 */
  label?: string
  /** 权限编码 */
  permissionCode?: string
  /** 权限类型:1-目录,2-菜单,3-按钮/接口 */
  permissionType?: number
  /** 路由路径 */
  routePath?: string
  /** 组件路径 */
  component?: string
  /** 菜单图标 */
  icon?: string
  /** 排序值 */
  sortOrder?: number
  /** 状态:0-禁用,1-启用 */
  status?: number
  children?: unknown[]
}
