/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 新建权限或菜单请求体
 */
export interface SysPermissionCreateRequest {
  /** 父级权限ID，根节点可为空 */
  parentId?: number
  /**
   * 权限名称
   * @minLength 1
   */
  permissionName: string
  /**
   * 权限编码，需要保持唯一
   * @minLength 1
   */
  permissionCode: string
  /** 权限类型:1-目录,2-菜单,3-按钮/接口 */
  permissionType: number
  /** 前端路由 */
  routePath?: string
  /** 前端组件路径 */
  component?: string
  /** 菜单图标 */
  icon?: string
  /** 排序值 */
  sortOrder?: number
  /** 状态:0-禁用,1-启用 */
  status: number
  /** 备注 */
  remark?: string
}
