/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 权限或菜单返回数据
 */
export interface SysPermissionVO {
  /** 权限ID */
  id?: string
  /** 父级权限ID */
  parentId?: number
  /** 权限名称 */
  permissionName?: string
  /** 权限编码 */
  permissionCode?: string
  /** 权限类型:1-目录,2-菜单,3-按钮/接口 */
  permissionType?: number
  /** 前端路由 */
  routePath?: string
  /** 前端组件 */
  component?: string
  /** 菜单图标 */
  icon?: string
  /** 排序值 */
  sortOrder?: number
  /** 状态:0-禁用,1-启用 */
  status?: number
  /** 备注 */
  remark?: string
  /** 创建时间 */
  createdAt?: string
  /** 最后更新时间 */
  updatedAt?: string
}
