/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 更新角色请求体
 */
export interface SysRoleUpdateRequest {
  /** 角色名称 */
  roleName?: string
  /** 角色类型:1-后台,2-前台,3-通用 */
  roleType?: number
  /** 数据范围:1-仅本人,2-本部门,3-本部门及子部门,4-自定义,5-全部 */
  dataScope?: number
  /** 排序值 */
  sortOrder?: number
  /** 状态:0-禁用,1-启用 */
  status?: number
  /** 备注 */
  remark?: string
}
