/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 角色权限关联数据
 */
export interface SysRolePermissionVO {
  /** 角色ID */
  roleId?: string
  /** 权限ID */
  permissionId?: string
}
