/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 角色绑定权限请求体
 */
export interface SysRolePermissionCreateRequest {
  /** 角色ID */
  roleId: number
  /** 权限ID */
  permissionId: number
}
