/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 更新角色绑定权限请求体
 */
export interface SysRolePermissionUpdateRequest {
  /** 角色ID */
  roleId: number
  /** 当前权限ID */
  permissionId: number
  /** 新权限ID */
  newPermissionId: number
}
