/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 系统角色返回数据
 */
export interface SysRoleVO {
  /** 角色ID */
  id?: string
  /** 角色编码 */
  roleCode?: string
  /** 角色名称 */
  roleName?: string
  /** 角色类型:1-后台,2-前台,3-通用 */
  roleType?: number
  /** 数据范围 */
  dataScope?: number
  /** 排序值 */
  sortOrder?: number
  /** 状态:0-禁用,1-启用 */
  status?: number
  /** 备注 */
  remark?: string
  /** 创建时间 */
  createdAt?: string
  /** 最后更新时间 */
  updatedAt?: string
}
