/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 用户角色关联数据
 */
export interface SysUserRoleVO {
  /** 用户ID */
  userId?: string
  /** 角色ID */
  roleId?: string
}
