/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 更新用户绑定角色请求体
 */
export interface SysUserRoleUpdateRequest {
  /** 用户ID */
  userId: number
  /** 当前角色ID */
  roleId: number
  /** 要变更的新角色ID */
  newRoleId: number
}
