/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 新建系统用户请求体
 */
export interface SysUserCreateRequest {
  /**
   * 登录账号，仅支持字母数字下划线
   * @minLength 4
   * @maxLength 20
   */
  username: string
  /**
   * 初始密码，服务端会进行加密处理
   * @minLength 6
   * @maxLength 32
   */
  password: string
  /** 真实姓名 */
  realName?: string
  /** 昵称 */
  nickname?: string
  /** 邮箱 */
  email?: string
  /** 手机号 */
  mobile?: string
  /** 头像地址 */
  avatarUrl?: string
  /** 性别:0-未知,1-男,2-女 */
  gender?: string
  /** 用户类型:1-管理员,2-普通用户 */
  userType: string
  /** 状态:0-禁用,1-启用 */
  status: string
}
