/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 用户绑定角色请求体
 */
export interface SysUserRoleCreateRequest {
  /** 用户ID */
  userId: number
  /** 角色ID */
  roleId: number
}
