/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TokenVO {
  /** token名称 */
  tokenName?: string
  /** token值 */
  tokenValue?: string
}
