/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserEmailLoginRequest {
  /**
   * 登录邮箱
   */
  email: string
  /**
   * 邮箱验证码
   */
  verificationCode: string
  /**
   * 用户类型，1为管理员，2为普通用户
   */
  userType?: string
}
