/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserRegisterRequest {
  /**
   * 用户名，仅支持字母、数字或下划线组合
   * @minLength 4
   * @maxLength 20
   * @pattern ^[a-zA-Z0-9_]+$
   */
  username: string
  /**
   * 登录密码
   * @minLength 6
   * @maxLength 32
   * @pattern ^\S+$
   */
  password: string
  /**
   * 确认密码，需要与密码一致
   * @minLength 1
   */
  confirmPassword: string
  /**
   * 验证码
   * @minLength 1
   */
  verificationCode: string
  /**
   * 验证码ID
   * @minLength 1
   */
  verificationCodeId: string
}
