/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserEmailLoginCodeRequest {
  /**
   * 接收验证码的邮箱地址
   */
  email: string
  /**
   * 用户类型，1为管理员，2为普通用户
   */
  userType?: string
}
