/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserLoginRequest {
  /**
   * 用户昵称
   * @minLength 1
   */
  username: string
  /**
   * 用户密码
   * @minLength 1
   */
  password: string
  /**
   * 用户类型，1为管理员，2为普通用户
   * @pattern ^[1-2]$
   */
  userType?: string
  /**
   * 验证码ID
   * @minLength 1
   */
  verificationCodeId: string
  /**
   * 验证码
   * @minLength 1
   */
  verificationCode: string
}
