/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface VerificationCodeVO {
  /** 验证码ID，于Redis对应，用用于查询Redis中的验证码 */
  codeId?: string
  /** 验证码的base64编码图片，用于前端展示！ */
  imageBase64?: string
}
